# src/main/resources/application.yml
server:
  port: 8080

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      # password: ${REDIS_PASSWORD:}   # 필요 시

# 프론트가 다른 포트/도메인일 때 CORS 허용 목록
app:
  cors:
    allowed-origins: "http://localhost:5500,http://127.0.0.1:5500,http://localhost:8080"